## Factorization

In [1]:
import numpy as np

In [2]:
import time

In [42]:
class GaussianElimination:
    @staticmethod
    def Elimination( A ):
        """
        Eliminacja Gaussa bez wyboru elementu podstawowego

        :param np.array A: Macierz uzupelnien o wymiarach (n,n+1) 
        :return np.array E: Macierz uzupelnien o wymiarach (n,n+1) 
        """
        n = A.shape[0]  # Ilosc wierszy w macierzy
        E = A.copy()      # Kopia macierzy A
        
        for i in range(n): # Dla kazdego wiersza
            factor = (E[i+1:, i] / E[i, i])          # Wyznaczenie wektora z mnoznikami
            E[i+1:] -= (factor[:, np.newaxis] * E[i]) # Wyzerowanie wierszy ponizej i
            
        return(E)
    
    
    @staticmethod
    def EliminationWithPivoting( A ):
        """
        Eliminacja Gaussa z wyborem elementu podstawowego (manipulacja wierszami).

        :param np.array A: Macierz uzupelnien o wymiarach (n,n+1) 
        :return np.array E: Macierz uzupelnien o wymiarach (n,n+1) 
        """
        n = A.shape[0]  # Ilosc wierszy w macierzy
        E = A.copy()    # Kopia macierzy A

        for i in range(n):
            E = GaussianElimination.__Pivoting(E, i)# Metoda wyboru elementu podstawowego
            factor = E[i+1:, i] / E[i, i]             # Wyznaczenie wektora z mnoznikami
            E[i+1:] -= (factor[:, np.newaxis] * E[i]) # Wyzerowanie wierszy ponizej i
            
        return(E)
    
    
    @staticmethod
    def __Pivoting( A, i):
        """
        Wybor elementu podstawowego max{abs{a(i,i)}}
        
        :param np.array A: Macierz uzupelnien o wymiarach (n,n+1) 
        :param u_int <= n : Pozycja dla szukanego maksimum
        :return np.array E: Macierz uzupelnien o wymiarach (n,n+1) 
        """
        pos_max_val = np.argmax( np.abs(A[i:,i]) ) + i # Pozycja najwyzszej wartosci absolutnej od i-tego wiersz
        if( A[i,i] == A[pos_max_val,i] ):              # Jezeli nie dokonujemy zamiany wierszy
            return A                                   # Zwroc macierz bez zmian
        
        # Zamiana wierszy 
        temp_row = A[i,:].copy()
        A[i,:]   = A[pos_max_val,:]
        A[pos_max_val] = temp_row
        
        return A            # Zwroc macierz z zamienionymi wierszami   
    
    
    @staticmethod
    def SolveLinearEquation( A, b ):
        """
        Funkcja realizuje rozwiazanie rownan liniowych z wykorzytaniem 
        metody eliminacji Gaussa oraz podstawienia wstecznego
        
        :param np.array A: Macierz wspolczynnikow
        :param np.array b: Wektor stalych
        :return np.array y: Wektor rozwiazan
        """
        
        Ab = np.append(A,b, axis=1)
        
        G = GaussianElimination.Elimination(Ab)
        y = Substitution.Backward(G[:,:G.shape[1]-1], 
                                  G[:,[G.shape[1]-1]])
        return y
    
    
    @staticmethod
    def SolveLinearEquationWithPivoting( A, b ):
        """
        Funkcja realizuje rozwiazanie rownan liniowych z wykorzytaniem 
        metody eliminacji Gaussa z pivotingiem oraz podstawienia wstecznego
        
        :param np.array A: Macierz wspolczynnikow
        :param np.array b: Wektor stalych
        :return np.array y: Wektor rozwiazan
        """
        
        Ab = np.append(A,b, axis=1)
        
        G = GaussianElimination.EliminationWithPivoting(Ab)
        y = Substitution.Backward(G[:,:G.shape[1]-1], 
                                  G[:,[G.shape[1]-1]])
        return y
        

---
## Faktoryzacja LU: Metoda Doolittle’a
$$ A = LU $$

$$
{\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\cdots &a_{nn}\end{bmatrix}}={\begin{bmatrix}1&0&\cdots &0\\l_{21}&1&\cdots &0\\\vdots &\vdots &\ddots &0\\l_{n1}&l_{n2}&\cdots &1\end{bmatrix}}\cdot {\begin{bmatrix}u_{11}&u_{12}&\cdots &u_{1n}\\0&u_{22}&\cdots &u_{2n}\\\vdots &\vdots &\ddots &\vdots \\0&0&\cdots &u_{nn}\end{bmatrix}}
$$

$ u_{ij}=a_{ij}-\sum _{k=1}^{i-1}l_{ik}u_{kj}$ for $j\in \{i,\ i+1,\ldots ,\ n\}$ (1)

$ l_{ji}={\frac {1}{u_{ii}}}\left(a_{ji}-\sum _{k=1}^{i-1}l_{jk}u_{ki}\right)$ for $j\in \{i+1,\ i+2,\ldots ,\ n\}$ (2)

---
## Faktoryzacja QR: Metoda GramaSchmidta

Faktoryzacja QR macierzy $\boldsymbol{A} \in \Re^{n x n}$, $\boldsymbol{A} = [\boldsymbol{a_1,a_2,...,a_n}]$

    Dla k=1:
$$\boldsymbol{u_1} \leftarrow \boldsymbol{\frac{a_1}{||a_1||}} (1)$$ 
    
    Dla k>1:
$$ \boldsymbol{ u_k \leftarrow a_k - \sum_{i=1}^{k-1} \langle u_i,a_k \rangle u_i  } (2)$$

$$\boldsymbol{u_k} \leftarrow \boldsymbol{\frac{u_k}{||u_k||}} (3)$$

---
$$ \boldsymbol{Q = [u_1, u_2,...,u_n]} $$

$$
\boldsymbol{R} =
\begin{bmatrix}
    \langle u_1,a_1 \rangle & \langle u_1,a_2 \rangle & \langle u_1,a_3 \rangle & \cdots \\
     0 & \langle u_2,a_2 \rangle & \langle u_2,a_3 \rangle & \cdots \\
     0 & 0 & \langle u_2,a_3 \rangle &\cdots \\
     \vdots & \vdots & \vdots & \ddots
 \end{bmatrix} (4)
$$

In [43]:
class Factorization:
    @staticmethod
    def LUDollitleMethod( A ):
        """
        Faktoryzacja macierzy A na LU metodą Dollitle
        
        :param np.array A: Tablica o wymiarach (n,n) 
        :return np.array L, U: Tablica o wymiarach (n,n) 
        """ 
        m, n = A.shape       # Wymiary macierzy A
    
        U = np.zeros((m, m)) # Macierz zerowa o wymiarach (m,m) typu float
        L = np.eye(m)        # Macierz jednostkowa o wymiarach (m,m) typu float

        for i in range(m):   
            U[i, i:] = A[i, i:] - (L[i,:i] @ U[:i,i:])                   # Wyznacza i-ty wiersz macierzy U (1)  
            L[(i+1):,i] = (A[(i+1):,i] - L[(i+1):,:] @ U[:,i]) / U[i, i] # Wyznacza i-ta kolumne macierzy L (2)

        return L, U
    
    
    @staticmethod
    def QRGramaSchmidtaMethod( A ):
        """
        Faktoryzacja macierzy A na QR metodą Grama-Schmidta
        
        :param np.array A: Tablica o wymiarach (n,n) 
        :return np.array Q, R: Tablica o wymiarach (n,n) 
        """
        n = A.shape[0] # Wymiar macierzy 
        
        Q = np.zeros((n,n)) # Macierz zerowa o wymiarach (n,n) typu float  
        R = np.zeros((n,n)) # Macierz zerowa o wymiarach (n,n) typu float
        
        for i in range(0, n):
            q = A[:,[i]]- Q[:,:i] @ ( (A[:,[i]].T @ Q[:,:i]).T )  # Wyznacza i-ta kolumne macierzy Q (2)
            Q[:,[i]] = q/np.linalg.norm(q)                        # Standaryzaczja i-tej kolumny (3)
            
            R[:(i+1),[i]] = Q[:,:(i+1)].T @ A[:,[i]]  # Wyznacznie i-tej kolumny macierzy R (4)
        return Q, R
        

## Substitution
---
* Forward

$${\begin{bmatrix}l_{11}&0&\cdots &0\\l_{21}&l_{22}&\cdots &0\\\vdots &\vdots &\ddots &0\\l_{n1}&l_{n2}&\cdots &l_{nn}\end{bmatrix}}
{{\begin{bmatrix}
y_{1}\\
y_{2}\\
\vdots\\
y_{n}\end{bmatrix}}}=
{{\begin{bmatrix}
b_{1}\\
b_{2}\\
\vdots\\
b_{n}\end{bmatrix}}}$$

$ y_{1} = \frac{b_1}{l_{11}}$

$ y_{i}=\frac{ b_i-\sum _{j=1}^{i-1}l_{ij}y_{j} } {l_{ii}}$ for $i\in \{2,\ldots ,\ n\}$

---
* Backward

$${\begin{bmatrix}u_{11}&u_{12}&\cdots &u_{1n}\\0&u_{22}&\cdots &u_{2n}\\\vdots &\vdots &\ddots &\vdots \\0&0&\cdots &u_{nn}\end{bmatrix}}{{\begin{bmatrix}
y_{1}\\
y_{2}\\
\vdots\\
y_{n}\end{bmatrix}}}=
{{\begin{bmatrix}
b_{1}\\
b_{2}\\
\vdots\\
b_{n}\end{bmatrix}}}$$

$y_n = \frac{b_n}{u_{nn}}$

$y_i = \frac{ b_i-\sum _{j=i+1}^{n}u_{ij}y_{j} } {u_{ii}}$ for $i\in \{1,\ldots ,\ n-1\}$


In [44]:
class Substitution:
    @staticmethod
    def Forward( L, b ):
        """
        Metoda realizuje podstawienie w przod
    
        :par np.array L: macierz wspolczynnikow (dolnotrojkatna)
        :par np.array b: wektor stalych 
        """
        rows = b.shape[0]      # Ilosc wierszy w macierzy
        y = np.zeros(b.shape)  # Wektor zerowy (n,1)
        y[0,0] = b[0,0]/L[0,0] # Wyznaczenie 0-wego elementu
        for i in range(1, rows):
            y[i,0] = (b[i,0]-L[i,:i]*y[:i,0])/L[i,i] # Wyznaczenie pozostalych elementow
        return y
    
    @staticmethod
    def Backward( U, b ):
        """
        Metoda realizuje podstawienie w przod
    
        :par np.array U: macierz wspolczynnikow (gornotrojkatna)
        :par np.array b: wektor stalych 
        """
        rows = U.shape[0]      # Ilosc wierszy w macierzy
        y = np.zeros(b.shape)  # Wektor zerowy (n,1)
        y[rows-1, 0] = b[rows-1, 0]/U[rows-1, rows-1] # Wyznaczenie n-tego elementu
        for i in range(rows-2, -1, -1):
            y[i] = (b[i]-U[i,i:]@y[i:])/U[i,i] # Wyznaczenie pozostalych elementow
        return y

In [45]:
def CountdownTime( fun, arg, n=1000 ):
    """
    Funkcja mierzy czas wykonania funkcji dla zadanego parametru n razy.
    
    :par fun : Wskaznik na funkcje
    :par arg : Argumenty przekazywane do funkcji []
    :par n   : n krotne wykonanie funkcji
    """
    start = time.time()
    for i in range(n):
        fun(*arg)
    end = time.time()
    return end - start

# Realizacja zadań
---
#### Zadanie 1

In [46]:
A = np.array([[2., -1., 0., 0. ], 
              [-1., 2., -1., 0.], 
              [0., -1., 2., -1.], 
              [0., 0., -1., 2. ]]) 

b = np.array ([[0.], 
               [0.], 
               [0.], 
               [5.] ])

# Eliminacja Gaussa - zaimplementowana 
print("Zaimplementowana metoda eliminacja Gaussa:")
gaus = GaussianElimination.SolveLinearEquation
GaussianElimination.SolveLinearEquation(A,b)
print(gaus(A,b))
print("Pomiar czasu dla n=10000 :", CountdownTime( gaus, [A,b], 10000))
print()

# Rozwiazanie przy pomocy wbudowanych metod numpy
print("Rozwiazanie przy pomocy wbudowanych metod numpy:")
print(np.linalg.solve(A,b))
print("Pomiar czasu dla n=10000 :", CountdownTime( np.linalg.solve, [A,b], 10000))

Zaimplementowana metoda eliminacja Gaussa:
[[1.]
 [2.]
 [3.]
 [4.]]
Pomiar czasu dla n=10000 : 0.6285061836242676

Rozwiazanie przy pomocy wbudowanych metod numpy:
[[1.]
 [2.]
 [3.]
 [4.]]
Pomiar czasu dla n=10000 : 0.05877995491027832


---
#### Zadanie 2

In [50]:
A = np.array([ [1. , 1., 1.], 
               [-1., 2.,-1.], 
               [0. ,-1., 2.] ]) 


b = np.array ([ [1.], 
                [2.], 
                [1.] ])


# Eliminacja Gaussa - zaimplementowana 
print("Zaimplementowana metoda eliminacja Gaussa:")
gaus = GaussianElimination.SolveLinearEquation
print(gaus(A,b))
print("Pomiar czasu dla n=10000 :", CountdownTime( gaus, [A,b], 10000))
print()

# Rozwiazanie przy pomocy wbudowanych metod numpy
print("Rozwiazanie przy pomocy wbudowanych metod numpy:")
print(np.linalg.solve(A,b))
print("Pomiar czasu dla n=10000 :", CountdownTime( np.linalg.solve, [A,b], 10000))

Zaimplementowana metoda eliminacja Gaussa:
[[-1.]
 [ 1.]
 [ 1.]]
Pomiar czasu dla n=10000 : 0.47539353370666504

Rozwiazanie przy pomocy wbudowanych metod numpy:
[[-1.]
 [ 1.]
 [ 1.]]
Pomiar czasu dla n=10000 : 0.05673861503601074


---
#### Zadanie 3

In [60]:
A = np.array( [ [0.0001, 1.], 
                [1., 1.] ] )

b = np.array( [ [1], 
                [2] ] )

# Eliminacja Gaussa - zaimplementowana 
print("Zaimplementowana metoda eliminacja Gaussa:")
gaus = GaussianElimination.SolveLinearEquation
GaussianElimination.SolveLinearEquation(A,b)
print(gaus(A,b))
print("Pomiar czasu dla n=10000 :", CountdownTime( gaus, [A,b], 10000))
print("Wyznacznik uwarunkowania macierzy: ",np.linalg.cond(A))
print()

# Rozwiazanie przy pomocy wbudowanych metod numpy
print("Rozwiazanie przy pomocy wbudowanych metod numpy:")
print(np.linalg.solve(A,b))
print("Pomiar czasu dla n=10000 :", CountdownTime( np.linalg.solve, [A,b], 10000))

Zaimplementowana metoda eliminacja Gaussa:
[[1.00010001]
 [0.99989999]]
Pomiar czasu dla n=10000 : 0.39073610305786133
Wyznacznik uwarunkowania macierzy:  2.6183852736548263

Rozwiazanie przy pomocy wbudowanych metod numpy:
[[1.00010001]
 [0.99989999]]
Pomiar czasu dla n=10000 : 0.09224987030029297


---
#### Zadanie 4

In [69]:
A = np.array( [ [ 0.835,  0.667], 
                [ 0.333, 0.266] ] )

b = np.array( [ [0.168], 
                [0.067] ] )

# Eliminacja Gaussa - zaimplementowana 
print("Zaimplementowana metoda eliminacja Gaussa:")
gaus = GaussianElimination.SolveLinearEquation
GaussianElimination.SolveLinearEquation(A,b)
print(gaus(A,b))
print("Pomiar czasu dla n=10000 :", CountdownTime( gaus, [A,b], 10000))
print("Wyznacznik uwarunkowania macierzy: ",np.linalg.cond(A))
print()

# Rozwiazanie przy pomocy wbudowanych metod numpy
print("Rozwiazanie przy pomocy wbudowanych metod numpy:")
print(np.linalg.solve(A,b))
print("Pomiar czasu dla n=10000 :", CountdownTime( np.linalg.solve, [A,b], 10000))

Zaimplementowana metoda eliminacja Gaussa:
[[ 1.]
 [-1.]]
Pomiar czasu dla n=10000 : 0.365401029586792
Wyznacznik uwarunkowania macierzy:  1323759.0000018796

Rozwiazanie przy pomocy wbudowanych metod numpy:
[[ 1.]
 [-1.]]
Pomiar czasu dla n=10000 : 0.06964254379272461


---
#### Zadanie 5