In [1]:
import numpy as np

In [95]:
def Landweber(A, b, iter_=30, alp_=None):
    """
    Implementacja metody iteracyjnej Landwebera
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    alp_  : relaxation parameter alp_>0 
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    # Set relaxation parameter if not given: alp=1/|max(eigA.T A)| 
    if alp_ == None:
        alp_ = 1 / np.abs(np.max(np.linalg.eig(A.T@A)[0]))  
    
    x = np.zeros( (iter_, A.shape[1], 1) )   
    invS = np.linalg.inv( (1/alp_)*np.eye(A.shape[1]) )
    T = (1/alp_)*np.eye(A.shape[1])-A.T@A
    
    for i in range(iter_):
        G = invS@T
        c = invS@b
        x[i] = G@x[i-1]+c
    return x

In [77]:
def GaussSeidel(A, b, iter_=30):
    """
    Implementacja metody iteracyjnej Gaussa-Sidela
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    x = np.zeros( (iter_, A.shape[1], 1) )
    invS = np.linalg.inv(np.tril(A, 0))
    T = -np.triu(A, 1)
    
    for i in range(iter_):
        G = invS@T
        c = invS@b
        x[i] = G@x[i-1]+c
    return x

In [78]:
def Jacobi(A, b, iter_=30):
    """
    Implementacja metody iteracyjnej Jacobiego
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    x = np.zeros( (iter_, A.shape[1], 1) )
    invS = np.reciprocal(np.diag(A))[np.newaxis]
    T = -A+np.diag(np.diag(A))    
    
    for i in range(iter_):
        G = invS*T
        c = invS.T*b
        x[i] = G@x[i-1]+c
    return x

In [79]:
def SuccessiveOverRelaxation(A, b, omeg_=1, iter_=30):
    """
    Implementacja metody iteracyjnej Successive Over-Relaxation (SOR)
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    omeg_ : relaxation parametr omeg_ in (0,2)
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """ 
    x = np.zeros( (iter_, A.shape[1], 1) )
    invS = np.linalg.inv( np.tril(A,-1) + (1/omeg_)*np.diag(np.diag(A)) )
    T = -(np.triu(A,1)+ ((omeg_-1)/omeg_)*np.diag(np.diag(A)))
    
    for i in range(iter_):
        G = invS@T
        c = invS@b
        x[i] = G@x[i-1]+c
    return x

In [109]:
def SteepestDescen(A, b, iter_=30):
    """
    Implementacja metody iteracyjnej SteepestDescen (SD)
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    x = np.zeros( (iter_, A.shape[1], 1) )
    
    for i in range(iter_):
        r = b-A@x[i-1]
        g = -A.T@r
        w = A@g
        alp_ = (g.T@g)/(w.T@w)
        x[i] = x[i-1]-alp_*g
    return x

In [ ]:
def Kaczmarz(A, b):
    pass

---
## Zadanie 1

$$x^{n-1} = D^{-1}b-D^{-1}Lx^{n+1}-D^{-1}Ux^{n}$$

In [112]:
A = np.array([[2,-1,0,0],
              [-1,2,-1,0],
              [0,-1,2,-1],
              [0,0,-1,2]],dtype=np.double)
b = np.array([0,0,0,5],
             dtype=np.double).reshape(4,1)
x = np.linalg.inv(A)@b

x_pr = SteepestDescen(A,b)
print(x_pr)

[[[ 0.        ]
  [ 0.        ]
  [-0.5952381 ]
  [ 1.19047619]]

 [[ 0.07347428]
  [-0.44084568]
  [-0.18378212]
  [ 1.39620418]]

 [[-0.20915153]
  [-0.32360748]
  [-0.20546167]
  [ 1.79172578]]

 [[-0.21460794]
  [-0.51409724]
  [ 0.08678801]
  [ 1.86030964]]

 [[-0.37268314]
  [-0.4087774 ]
  [ 0.09841753]
  [ 2.0907007 ]]

 [[-0.35591677]
  [-0.50366597]
  [ 0.29331586]
  [ 2.13574335]]

 [[-0.43664273]
  [-0.40652383]
  [ 0.31231061]
  [ 2.28824581]]

 [[-0.40396204]
  [-0.4527708 ]
  [ 0.4577761 ]
  [ 2.31688554]]

 [[-0.44350237]
  [-0.35513093]
  [ 0.47583792]
  [ 2.42793345]]

 [[-0.39943531]
  [-0.37815661]
  [ 0.59654507]
  [ 2.44423686]]

 [[-0.41762956]
  [-0.27854804]
  [ 0.61027031]
  [ 2.53247526]]

 [[-0.36709806]
  [-0.2911396 ]
  [ 0.71749486]
  [ 2.54043016]]

 [[-0.37472803]
  [-0.19151152]
  [ 0.7272105 ]
  [ 2.61563826]]

 [[-0.32165868]
  [-0.19941357]
  [ 0.82598347]
  [ 2.61873023]]

 [[-0.32417968]
  [-0.10164981]
  [ 0.83305218]
  [ 2.68604126]]

 [[-0.2709