## Factorization

In [1]:
import numpy as np
import time

In [2]:
class GaussianElimination:
    @staticmethod
    def Elimination( A ):
        """
        Eliminacja Gaussa bez wyboru elementu podstawowego

        :param np.array A: Macierz uzupelnien o wymiarach (n,n+1) 
        :return np.array E: Macierz uzupelnien o wymiarach (n,n+1) 
        """
        n = A.shape[0]  # Ilosc wierszy w macierzy
        E = A.copy()      # Kopia macierzy A
        
        for i in range(n): # Dla kazdego wiersza
            factor = (E[i+1:, i] / E[i, i])          # Wyznaczenie wektora z mnoznikami
            E[i+1:] -= (factor[:, np.newaxis] * E[i]) # Wyzerowanie wierszy ponizej i
            
        return(E)
    
    
    @staticmethod
    def EliminationWithPivoting( A ):
        """
        Eliminacja Gaussa z wyborem elementu podstawowego (manipulacja wierszami).

        :param np.array A: Macierz uzupelnien o wymiarach (n,n+1) 
        :return np.array E: Macierz uzupelnien o wymiarach (n,n+1) 
        """
        n = A.shape[0]  # Ilosc wierszy w macierzy
        E = A.copy()    # Kopia macierzy A

        for i in range(n):
            E = GaussianElimination.__Pivoting(E, i)# Metoda wyboru elementu podstawowego
            factor = E[i+1:, i] / E[i, i]             # Wyznaczenie wektora z mnoznikami
            E[i+1:] -= (factor[:, np.newaxis] * E[i]) # Wyzerowanie wierszy ponizej i
            
        return(E)
    
    
    @staticmethod
    def __Pivoting( A, i):
        """
        Wybor elementu podstawowego max{abs{a(i,i)}}
        
        :param np.array A: Macierz uzupelnien o wymiarach (n,n+1) 
        :param u_int <= n : Pozycja dla szukanego maksimum
        :return np.array E: Macierz uzupelnien o wymiarach (n,n+1) 
        """
        pos_max_val = np.argmax( np.abs(A[i:,i]) ) + i # Pozycja najwyzszej wartosci absolutnej od i-tego wiersz
        if( A[i,i] == A[pos_max_val,i] ):              # Jezeli nie dokonujemy zamiany wierszy
            return A                                   # Zwroc macierz bez zmian
        
        # Zamiana wierszy 
        temp_row = A[i,:].copy()
        A[i,:]   = A[pos_max_val,:]
        A[pos_max_val] = temp_row
        
        return A            # Zwroc macierz z zamienionymi wierszami   
    
    
    @staticmethod
    def SolveLinearEquation( A, b ):
        """
        Funkcja realizuje rozwiazanie rownan liniowych z wykorzytaniem 
        metody eliminacji Gaussa oraz podstawienia wstecznego
        
        :param np.array A: Macierz wspolczynnikow
        :param np.array b: Wektor stalych
        :return np.array y: Wektor rozwiazan
        """
        
        Ab = np.append(A,b, axis=1)
        
        G = GaussianElimination.Elimination(Ab)
        y = Substitution.Backward(G[:,:G.shape[1]-1], 
                                  G[:,[G.shape[1]-1]])
        return y
    
    
    @staticmethod
    def SolveLinearEquationWithPivoting( A, b ):
        """
        Funkcja realizuje rozwiazanie rownan liniowych z wykorzytaniem 
        metody eliminacji Gaussa z pivotingiem oraz podstawienia wstecznego
        
        :param np.array A: Macierz wspolczynnikow
        :param np.array b: Wektor stalych
        :return np.array y: Wektor rozwiazan
        """
        
        Ab = np.append(A,b, axis=1)
        
        G = GaussianElimination.EliminationWithPivoting(Ab)
        y = Substitution.Backward(G[:,:G.shape[1]-1], 
                                  G[:,[G.shape[1]-1]])
        return y
        

---
## Faktoryzacja LU: Metoda Doolittle’a
$$ A = LU $$

$$
{\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\cdots &a_{nn}\end{bmatrix}}={\begin{bmatrix}1&0&\cdots &0\\l_{21}&1&\cdots &0\\\vdots &\vdots &\ddots &0\\l_{n1}&l_{n2}&\cdots &1\end{bmatrix}}\cdot {\begin{bmatrix}u_{11}&u_{12}&\cdots &u_{1n}\\0&u_{22}&\cdots &u_{2n}\\\vdots &\vdots &\ddots &\vdots \\0&0&\cdots &u_{nn}\end{bmatrix}}
$$

$ u_{ij}=a_{ij}-\sum _{k=1}^{i-1}l_{ik}u_{kj}$ for $j\in \{i,\ i+1,\ldots ,\ n\}$ (1)

$ l_{ji}={\frac {1}{u_{ii}}}\left(a_{ji}-\sum _{k=1}^{i-1}l_{jk}u_{ki}\right)$ for $j\in \{i+1,\ i+2,\ldots ,\ n\}$ (2)

---
## Faktoryzacja QR: Metoda GramaSchmidta

Faktoryzacja QR macierzy $\boldsymbol{A} \in \Re^{n x n}$, $\boldsymbol{A} = [\boldsymbol{a_1,a_2,...,a_n}]$

    Dla k=1:
$$\boldsymbol{u_1} \leftarrow \boldsymbol{\frac{a_1}{||a_1||}} (1)$$ 
    
    Dla k>1:
$$ \boldsymbol{ u_k \leftarrow a_k - \sum_{i=1}^{k-1} \langle u_i,a_k \rangle u_i  } (2)$$

$$\boldsymbol{u_k} \leftarrow \boldsymbol{\frac{u_k}{||u_k||}} (3)$$

---
$$ \boldsymbol{Q = [u_1, u_2,...,u_n]} $$

$$
\boldsymbol{R} =
\begin{bmatrix}
    \langle u_1,a_1 \rangle & \langle u_1,a_2 \rangle & \langle u_1,a_3 \rangle & \cdots \\
     0 & \langle u_2,a_2 \rangle & \langle u_2,a_3 \rangle & \cdots \\
     0 & 0 & \langle u_2,a_3 \rangle &\cdots \\
     \vdots & \vdots & \vdots & \ddots
 \end{bmatrix} (4)
$$

In [3]:
class Factorization:
    @staticmethod
    def LUDollitleMethod( A ):
        """
        Faktoryzacja macierzy A na LU metodą Dollitle
        
        :param np.array A: Tablica o wymiarach (n,n) 
        :return np.array L, U: Tablica o wymiarach (n,n) 
        """ 
        m, n = A.shape       # Wymiary macierzy A
    
        U = np.zeros((m, m)) # Macierz zerowa o wymiarach (m,m) typu float
        L = np.eye(m)        # Macierz jednostkowa o wymiarach (m,m) typu float

        for i in range(m):   
            U[i, i:] = A[i, i:] - (L[i,:i] @ U[:i,i:])                   # Wyznacza i-ty wiersz macierzy U (1)  
            L[(i+1):,i] = (A[(i+1):,i] - L[(i+1):,:] @ U[:,i]) / U[i, i] # Wyznacza i-ta kolumne macierzy L (2)

        return L, U
    
    
    @staticmethod
    def QRGramaSchmidtaMethod( A ):
        """
        Faktoryzacja macierzy A na QR metodą Grama-Schmidta
        
        :param np.array A: Tablica o wymiarach (n,n) 
        :return np.array Q, R: Tablica o wymiarach (n,n) 
        """
        n = A.shape[0] # Wymiar macierzy 
        
        Q = np.zeros((n,n)) # Macierz zerowa o wymiarach (n,n) typu float  
        R = np.zeros((n,n)) # Macierz zerowa o wymiarach (n,n) typu float
        
        for i in range(0, n):
            q = A[:,[i]]- Q[:,:i] @ ( (A[:,[i]].T @ Q[:,:i]).T )  # Wyznacza i-ta kolumne macierzy Q (2)
            Q[:,[i]] = q/np.linalg.norm(q)                        # Standaryzaczja i-tej kolumny (3)
            
            R[:(i+1),[i]] = Q[:,:(i+1)].T @ A[:,[i]]  # Wyznacznie i-tej kolumny macierzy R (4)
        return Q, R
        
    

## Substitution
---
* Forward

$${\begin{bmatrix}l_{11}&0&\cdots &0\\l_{21}&l_{22}&\cdots &0\\\vdots &\vdots &\ddots &0\\l_{n1}&l_{n2}&\cdots &l_{nn}\end{bmatrix}}
{{\begin{bmatrix}
y_{1}\\
y_{2}\\
\vdots\\
y_{n}\end{bmatrix}}}=
{{\begin{bmatrix}
b_{1}\\
b_{2}\\
\vdots\\
b_{n}\end{bmatrix}}}$$

$ y_{1} = \frac{b_1}{l_{11}}$

$ y_{i}=\frac{ b_i-\sum _{j=1}^{i-1}l_{ij}y_{j} } {l_{ii}}$ for $i\in \{2,\ldots ,\ n\}$

---
* Backward

$${\begin{bmatrix}u_{11}&u_{12}&\cdots &u_{1n}\\0&u_{22}&\cdots &u_{2n}\\\vdots &\vdots &\ddots &\vdots \\0&0&\cdots &u_{nn}\end{bmatrix}}{{\begin{bmatrix}
y_{1}\\
y_{2}\\
\vdots\\
y_{n}\end{bmatrix}}}=
{{\begin{bmatrix}
b_{1}\\
b_{2}\\
\vdots\\
b_{n}\end{bmatrix}}}$$

$y_n = \frac{b_n}{u_{nn}}$

$y_i = \frac{ b_i-\sum _{j=i+1}^{n}u_{ij}y_{j} } {u_{ii}}$ for $i\in \{1,\ldots ,\ n-1\}$


In [4]:
class Substitution:
    @staticmethod
    def Forward( L, b ):
        """
        Metoda realizuje podstawienie w przod
    
        :par np.array L: macierz wspolczynnikow (dolnotrojkatna)
        :par np.array b: wektor stalych 
        """
        rows = b.shape[0]      # Ilosc wierszy w macierzy
        y = np.zeros(b.shape)  # Wektor zerowy (n,1)
        y[0,0] = b[0,0]/L[0,0] # Wyznaczenie 0-wego elementu
        for i in range(1, rows):
            y[i,0] = (b[i,0]-np.dot(L[i,:i], y[:i,0]))/L[i,i] # Wyznaczenie pozostalych elementow
            
        return y
    
    @staticmethod
    def Backward( U, b ):
        """
        Metoda realizuje podstawienie w przod
    
        :par np.array U: macierz wspolczynnikow (gornotrojkatna)
        :par np.array b: wektor stalych 
        """
        rows = U.shape[0]      # Ilosc wierszy w macierzy
        y = np.zeros(b.shape)  # Wektor zerowy (n,1)
        y[rows-1, 0] = b[rows-1, 0]/U[rows-1, rows-1] # Wyznaczenie n-tego elementu
        for i in range(rows-2, -1, -1):
            y[i] = (b[i]-U[i,i:]@y[i:])/U[i,i] # Wyznaczenie pozostalych elementow
        return y

In [5]:
def CountdownTime( fun, arg, n=1000 ):
    """
    Funkcja mierzy czas wykonania funkcji dla zadanego parametru n razy.
    
    :par fun : Wskaznik na funkcje
    :par arg : Argumenty przekazywane do funkcji []
    :par n   : n krotne wykonanie funkcji
    """
    start = time.time()
    for i in range(n):
        fun(*arg)
    end = time.time()
    return end - start

# Realizacja zadań
---
#### Zadanie 1

In [6]:
A = np.array([[2., -1., 0., 0. ], 
              [-1., 2., -1., 0.], 
              [0., -1., 2., -1.], 
              [0., 0., -1., 2. ]]) 

b = np.array ([[0.], 
               [0.], 
               [0.], 
               [5.] ])

# Eliminacja Gaussa - zaimplementowana 
print("Zaimplementowana metoda eliminacja Gaussa:")
gaus = GaussianElimination.SolveLinearEquation
GaussianElimination.SolveLinearEquation(A,b)
print(gaus(A,b))
print("Pomiar czasu dla n=1000 :", CountdownTime( gaus, [A,b]))
print()

# Rozwiazanie przy pomocy wbudowanych metod numpy
print("Rozwiazanie przy pomocy wbudowanych metod numpy:")
print(np.linalg.solve(A,b))
print("Pomiar czasu dla n=1000 :", CountdownTime( np.linalg.solve, [A,b]))

Zaimplementowana metoda eliminacja Gaussa:
[[1.]
 [2.]
 [3.]
 [4.]]
Pomiar czasu dla n=1000 : 0.07484006881713867

Rozwiazanie przy pomocy wbudowanych metod numpy:
[[1.]
 [2.]
 [3.]
 [4.]]
Pomiar czasu dla n=1000 : 0.010073184967041016


---
#### Zadanie 2

In [7]:
A = np.array([ [1. , 1., 1.], 
               [1. , 1., 2.], 
               [1. , 2., 2.] ]) 


b = np.array ([ [1.], 
                [2.], 
                [1.] ])


# Eliminacja Gaussa - zaimplementowana 
print("Zaimplementowana metoda eliminacja Gaussa:")
gaus = GaussianElimination.SolveLinearEquationWithPivoting
print(gaus(A,b))
print("Pomiar czasu dla n=1000 :", CountdownTime( gaus, [A,b]))
print()

# Rozwiazanie przy pomocy wbudowanych metod numpy
print("Rozwiazanie przy pomocy wbudowanych metod numpy:")
print(np.linalg.solve(A,b))
print("Pomiar czasu dla n=1000 :", CountdownTime( np.linalg.solve, [A,b]))

Zaimplementowana metoda eliminacja Gaussa:
[[ 1.]
 [-1.]
 [ 1.]]
Pomiar czasu dla n=1000 : 0.08092379570007324

Rozwiazanie przy pomocy wbudowanych metod numpy:
[[ 1.]
 [-1.]
 [ 1.]]
Pomiar czasu dla n=1000 : 0.007288455963134766


---
#### Zadanie 3

In [8]:
A = np.array( [ [0.0001, 1.], 
                [1., 1.] ] )

b = np.array( [ [1], 
                [2] ] )

print("Wyznacznik uwarunkowania macierzy: ",np.linalg.cond(A).round(3))

Wyznacznik uwarunkowania macierzy:  2.618


---
#### Zadanie 4

In [9]:
A = np.array( [ [ 0.835,  0.667], 
                [ 0.333, 0.266] ] )

b1 = np.array( [ [0.168], 
                 [0.067] ] )

b2 = np.array( [ [0.168], 
                 [0.066] ] )

# Rozwiazanie przy pomocy wbudowanych metod numpy 

print("Rozwiazanie dla b2 = 0.067:")
print(np.linalg.solve(A,b1))
print()

print("Rozwiazanie dla b2 = 0.066:")
print(np.linalg.solve(A,b2))
print()

print("Wskaznik uwarunkowania macierzy: ",np.linalg.cond(A).round(3))

Rozwiazanie dla b2 = 0.067:
[[ 1.]
 [-1.]]

Rozwiazanie dla b2 = 0.066:
[[-665.99999998]
 [ 833.99999998]]

Wskaznik uwarunkowania macierzy:  1323759.0


---
#### Zadanie 5

In [10]:
A = np.array( [[1, 2,3,4],
               [-1,1,2,1],
               [0, 2,1,3],
               [0, 0,1,1]], dtype=float)

# Faktoryzacja macierzy A na LU
L,U = Factorization.LUDollitleMethod(A)
print("Faktoryzacja LU metoda Dollitle:")
print("L = ")
print(L)
print("U = ")
print(U)
print()

# Wyznacznie wskaznika macierzy A z faktorow LU
# det(A) = det(L)*det(U), det(L)=1  ==> det(A) = det(U)
detA = np.product(np.diag(U))
print("Wyznacznik macierzy:")
print("det(A) = det(U) = ",detA)
print()

#Rozwiazanie ukladu rownan
b = np.array( [[1],
               [1],
               [1],
               [1],])
                                #LUx = b  -> Ux = v
v = Substitution.Forward(L,b)   #Lv = b
x = Substitution.Backward(U,v)  #Ux = v

print("Rozwiazanie ukladu rownan z faktoryzacja LU")
print(x.round(3))

Faktoryzacja LU metoda Dollitle:
L = 
[[ 1.          0.          0.          0.        ]
 [-1.          1.          0.          0.        ]
 [ 0.          0.66666667  1.          0.        ]
 [ 0.          0.         -0.42857143  1.        ]]
U = 
[[ 1.          2.          3.          4.        ]
 [ 0.          3.          5.          5.        ]
 [ 0.          0.         -2.33333333 -0.33333333]
 [ 0.          0.          0.          0.85714286]]

Wyznacznik macierzy:
det(A) = det(U) =  -6.0

Rozwiazanie ukladu rownan z faktoryzacja LU
[[-1.]
 [-1.]
 [ 0.]
 [ 1.]]


#### Zadanie 7

In [11]:
A = np.array([[-2,1,2,1],
              [2,-1,2,1],
              [2,3,-4,5],
              [2,3,0,-1]], dtype=float)

Q, R = Factorization.QRGramaSchmidtaMethod(A) 
print("Implementacja metody Grama Schmidta")
print("Faktory macierzy A")
print("Q=")
print(Q)
print("R=")
print(R)
print("Pomiar czasu dla n=1000 :", CountdownTime( Factorization.QRGramaSchmidtaMethod, [A]))
print()

print("Implementacja w numpy")
Q_n, R_n = np.linalg.qr(A)
print("Q_n=")
print(Q_n)
print("R_n=")
print(R_n)
print("Pomiar czasu dla n=1000 :", CountdownTime( np.linalg.qr, [A]))

Implementacja metody Grama Schmidta
Faktory macierzy A
Q=
[[-0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5  0.5]
 [ 0.5  0.5 -0.5  0.5]
 [ 0.5  0.5  0.5 -0.5]]
R=
[[ 4.  2. -2.  2.]
 [ 0.  4. -2.  2.]
 [ 0.  0.  4. -2.]
 [ 0.  0.  0.  4.]]
Pomiar czasu dla n=1000 : 0.1480274200439453

Implementacja w numpy
Q_n=
[[-0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5  0.5]
 [ 0.5  0.5 -0.5  0.5]
 [ 0.5  0.5  0.5 -0.5]]
R_n=
[[ 4.  2. -2.  2.]
 [ 0.  4. -2.  2.]
 [ 0.  0.  4. -2.]
 [ 0.  0.  0.  4.]]
Pomiar czasu dla n=1000 : 0.02861618995666504


#### Zadanie 8

In [16]:
M = 200
N = 30

I = np.eye(N)
C = np.random.rand(M,M)
A = np.kron(I,C.T@C)

b = np.random.randn(A.shape[0],1)

#Rozwiazanie metoda LU
print("Rozklad LU")
start = time.time()
L,U = Factorization.LUDollitleMethod(A)
v = Substitution.Forward(L,b)   #Lv = b
x = Substitution.Backward(U,v)  #Ux = v
end = time.time()
print("Czas wykonania: ",end-start)
print(x)
print()

#Rozwiazanie metoda QR
print("Rozklad QR")
start = time.time()
Q,R = Factorization.QRGramaSchmidtaMethod(A)
y = Q.T @ b                     #y = Q.T*b
x = Substitution.Backward(R,y)  #Rx = y
end = time.time()
print("Czas wykonania: ",end-start)
print(x)
print()

print("Eliminacja Gaussa")
start = time.time()
x = GaussianElimination.SolveLinearEquationWithPivoting(A,b)
end = time.time()
print("Czas wykonania: ",end-start)
print(x)
print()

Rozklad LU
Czas wykonania:  32.066895961761475
[[ 17.49298934]
 [222.67819581]
 [206.72077963]
 ...
 [-54.45694868]
 [ 85.98738381]
 [ 37.77257198]]

Rozklad QR
Czas wykonania:  106.65132308006287
[[ 17.49336429]
 [222.66289344]
 [206.70335992]
 ...
 [-54.44315281]
 [ 85.95622041]
 [ 37.7700819 ]]

Eliminacja Gaussa
Czas wykonania:  296.6508376598358
[[ 17.49298933]
 [222.67819581]
 [206.72077963]
 ...
 [-54.45694868]
 [ 85.98738381]
 [ 37.77257198]]

