In [3]:
import numpy as np

In [28]:
def GaussSeidel(A, b, iter_=30):
    """
    Implementacja metody iteracyjnej Gaussa-Sidela
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    x = np.zeros( (iter_, A.shape[1], 1) )
    invS = np.linalg.inv(np.tril(A, 0))
    T = -np.triu(A, 1)
    
    for i in range(iter_):
        G = invS@T
        c = invS@b
        x[i] = G@x[i-1]+c
    return x

In [5]:
def iterable(A,b, iter_=20):
    L = np.tril(A, -1)
    D = np.diag(np.diag(A))
    U = np.triu(A, 1)
    invD = np.linalg.inv(D)
    x = np.zeros((A.shape[1],1))
    for _ in iter_:
        
    
    
    

SyntaxError: unexpected EOF while parsing (2504307727.py, line 11)

---
## Zadanie 1

$$x^{n-1} = D^{-1}b-D^{-1}Lx^{n+1}-D^{-1}Ux^{n}$$

In [27]:
A = np.array([[2,-1,0,0],
              [-1,2,-1,0],
              [0,-1,2,-1],
              [0,0,-1,2]])
b = np.array([0,0,0,5]).reshape(4,1)
x = np.linalg.inv(A)@b

x_sol = GaussSeidel(A,b)
print(x_sol)
dia = np.diag(np.diag(A))
print(np.linalg.inv(dia))
print(np.diag(A))

[[[0.        ]
  [0.        ]
  [0.        ]
  [2.5       ]]

 [[0.        ]
  [0.        ]
  [1.25      ]
  [3.125     ]]

 [[0.        ]
  [0.625     ]
  [1.875     ]
  [3.4375    ]]

 [[0.3125    ]
  [1.09375   ]
  [2.265625  ]
  [3.6328125 ]]

 [[0.546875  ]
  [1.40625   ]
  [2.51953125]
  [3.75976562]]

 [[0.703125  ]
  [1.61132812]
  [2.68554688]
  [3.84277344]]

 [[0.80566406]
  [1.74560547]
  [2.79418945]
  [3.89709473]]

 [[0.87280273]
  [1.83349609]
  [2.86529541]
  [3.93264771]]

 [[0.91674805]
  [1.89102173]
  [2.91183472]
  [3.95591736]]

 [[0.94551086]
  [1.92867279]
  [2.94229507]
  [3.97114754]]

 [[0.9643364 ]
  [1.95331573]
  [2.96223164]
  [3.98111582]]

 [[0.97665787]
  [1.96944475]
  [2.97528028]
  [3.98764014]]

 [[0.98472238]
  [1.98000133]
  [2.98382074]
  [3.99191037]]

 [[0.99000067]
  [1.9869107 ]
  [2.98941053]
  [3.99470527]]

 [[0.99345535]
  [1.99143294]
  [2.9930691 ]
  [3.99653455]]

 [[0.99571647]
  [1.99439279]
  [2.99546367]
  [3.99773184]]

 [[0.997

In [23]:
z = np.zeros((10,3,1))
z[0] = np.ones((3,1))
print(z)

[[[1.]
  [1.]
  [1.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]


In [ ]:
# W Jacobim trzeba używać pivotingu