In [1]:
import numpy as np

In [95]:
def Landweber(A, b, iter_=30, alp_=None):
    """
    Implementacja metody iteracyjnej Landwebera
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    alp_  : relaxation parameter alp_>0 
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    # Set relaxation parameter if not given: alp=1/|max(eigA.T A)| 
    if alp_ == None:
        alp_ = 1 / np.abs(np.max(np.linalg.eig(A.T@A)[0]))  
    
    x = np.zeros( (iter_, A.shape[1], 1) )   
    invS = np.linalg.inv( (1/alp_)*np.eye(A.shape[1]) )
    T = (1/alp_)*np.eye(A.shape[1])-A.T@A
    
    for i in range(iter_):
        G = invS@T
        c = invS@b
        x[i] = G@x[i-1]+c
    return x

In [77]:
def GaussSeidel(A, b, iter_=30):
    """
    Implementacja metody iteracyjnej Gaussa-Sidela
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    x = np.zeros( (iter_, A.shape[1], 1) )
    invS = np.linalg.inv(np.tril(A, 0))
    T = -np.triu(A, 1)
    
    for i in range(iter_):
        G = invS@T
        c = invS@b
        x[i] = G@x[i-1]+c
    return x

In [78]:
def Jacobi(A, b, iter_=30):
    """
    Implementacja metody iteracyjnej Jacobiego
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    x = np.zeros( (iter_, A.shape[1], 1) )
    invS = np.reciprocal(np.diag(A))[np.newaxis]
    T = -A+np.diag(np.diag(A))    
    
    for i in range(iter_):
        G = invS*T
        c = invS.T*b
        x[i] = G@x[i-1]+c
    return x

In [79]:
def SuccessiveOverRelaxation(A, b, omeg_=1, iter_=30):
    """
    Implementacja metody iteracyjnej Successive Over-Relaxation (SOR)
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    omeg_ : relaxation parametr omeg_ in (0,2)
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """ 
    x = np.zeros( (iter_, A.shape[1], 1) )
    invS = np.linalg.inv( np.tril(A,-1) + (1/omeg_)*np.diag(np.diag(A)) )
    T = -(np.triu(A,1)+ ((omeg_-1)/omeg_)*np.diag(np.diag(A)))
    
    for i in range(iter_):
        G = invS@T
        c = invS@b
        x[i] = G@x[i-1]+c
    return x

In [109]:
def SteepestDescen(A, b, iter_=30):
    """
    Implementacja metody iteracyjnej SteepestDescen (SD)
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    x = np.zeros( (iter_, A.shape[1], 1) )
    
    for i in range(iter_):
        r = b-A@x[i-1]
        g = -A.T@r
        w = A@g
        alp_ = (g.T@g)/(w.T@w)
        x[i] = x[i-1]-alp_*g
    return x

In [177]:
def Kaczmarz(A, b, alp_=1, iter_ = 30):
    """
    Implementacja metody iteracyjnej Kaczmarza
    Parameters
    ----------
    A : numpy.array (matrix) - equation matrix
    b : numpy.array (vector) - unknown vector
    alp_ : relaxation parametr alp_ (0,2)
    iter_ : number of iteration
    
    Returns
    ----------
    x : numpy.array (vector) - solve for n-th itereations
    """
    
    x = np.zeros( (iter_, A.shape[1], 1) )
    l = np.power(np.linalg.norm(A, axis=1), 2)
    
    for j in range(iter_):
        x[j] = x[j-1]
        for i in range(A.shape[0]):
            x[j] += alp_*((b[i]-A[i,:]@x[j])/l[i])*A[[i],:].T
    return x

---
## Zadanie 1

$$x^{n-1} = D^{-1}b-D^{-1}Lx^{n+1}-D^{-1}Ux^{n}$$

In [179]:
A = np.array([[2,-1,0,0],
              [-1,2,-1,0],
              [0,-1,2,-1],
              [0,0,-1,2]],dtype=np.double)
b = np.array([0,0,0,5],
             dtype=np.double).reshape(4,1)
x = np.linalg.inv(A)@b




[[[ 0.        ]
  [ 0.        ]
  [-1.        ]
  [ 2.        ]]

 [[ 0.16666667]
  [-0.88888889]
  [-0.2       ]
  [ 2.4       ]]

 [[-0.45      ]
  [-0.83333333]
  [ 0.23111111]
  [ 2.61555556]]

 [[-0.67351852]
  [-0.7308642 ]
  [ 0.49244444]
  [ 2.74622222]]

 [[-0.72264815]
  [-0.61117284]
  [ 0.67389136]
  [ 2.83694568]]

 [[-0.69581337]
  [-0.48743896]
  [ 0.81612444]
  [ 2.90806222]]

 [[-0.63722813]
  [-0.36541283]
  [ 0.93763181]
  [ 2.9688159 ]]

 [[-0.5666881 ]
  [-0.24750685]
  [ 1.04689796]
  [ 3.02344898]]

 [[-0.49299353]
  [-0.13463854]
  [ 1.14789243]
  [ 3.07394622]]

 [[-0.41999659]
  [-0.02706048]
  [ 1.24254305]
  [ 3.12127153]]

 [[-0.34932577]
  [ 0.07526627]
  [ 1.33185073]
  [ 3.16592537]]

 [[-0.28161309]
  [ 0.1725042 ]
  [ 1.41639205]
  [ 3.20819603]]

 [[-0.21704675]
  [ 0.2648642 ]
  [ 1.49654606]
  [ 3.24827303]]

 [[-0.15561985]
  [ 0.35257197]
  [ 1.57259677]
  [ 3.28629839]]

 [[-0.09724224]
  [ 0.43585329]
  [ 1.64477967]
  [ 3.32238983]]

 [[-0.0417